### ISSUE TITLE
Refactor excess code in StudentCard component

### ISSUE THREAD

**Issue by kammanz** [kammanz/student-search#3]
After user adds a tag to student card, I need the input value to return to its placeholder value, "add a tag". I got it to work but my solution might be hacky, I wanted to use set state, but I couldn't get it to work. So wanna know about best practice here.  @ studentcard.js, line 46

**Comment by Tumne** [comment]
Let's refactor the code:

- [ ] remove `searchtag` as a prop in Student.js
- [ ] remove `searchtag` state and commented out code in StudentCard.js
- [ ] change StudentCard.js into a functional componen
