### ISSUE TITLE
Fix font stylings

### ISSUE THREAD

**Issue by Tumne** [kammanz/student-search#5]
Noticed the font colour and sizes are off compared to designs. please refer to the original designs

- [x] search tags input text should be light grey colour
<img width="294" alt="Screen Shot 2019-11-13 at 1 32 12 PM" src="https://user-images.githubusercontent.com/623755/68792773-0f125f00-061a-11ea-8654-bf850ceb8be6.png">

- [x] All text within studentCard should also be light grey:

<img width="292" alt="Screen Shot 2019-11-13 at 1 30 49 PM" src="https://user-images.githubusercontent.com/623755/68792723-f2762700-0619-11ea-8bbd-833942ce14b2.png">

- [x] Name titles font should be a bit larger size
- [x] `+` and `-` signs font should be larger size and bolder

**Comment by kammanz** [comment]
Upon closer inspection, it looks like the font color for search tags and within the student card is dark grey, not light. I have updated them and made them uniform.
